### ISSUE TITLE
I click on the tag editor will crash

### ISSUE THREAD

**Issue by jacktau** [triverske/ultimatearena#32]
---
###### 

FATAL ERROR in
action number 1
of Mouse Event for Glob Left Released
for object oUIListBox:

Push :: Execution Error - Variable Index [0,-1] out of range [1,1] - -1.ypos(100146,-1)
at gml_Object_oUIListBox_Mouse_56
######

**Comment by triverske** [comment]
Thanks for the report, we'll get on this.
