### ISSUE TITLE
NAMING ERROR character. Cannot delete 

### ISSUE THREAD

**Issue by Crackshaw** [triverske/ultimatearena#49]
So I was editing some of my characters in the Editor and I noticed a new NAMING ERROR character. For some reason, the NAMING ERROR character will not delete from the editor list like it has all the other times I've had this error. No matter how many times I re-open the game, click delete or re-name the character, it's sticking out like a sore thumb in the character list.

**Comment by triverske** [comment]
Do you have the steps to reproduce this bug?

**Comment by Crackshaw** [comment]
The NAMING ERROR character first popped up when I accidentally put a period in a name and saved. I also noticed that if I tried to re-name the character and delete it, another NAMING ERROR popped up at the bottom which went away once I exited the editor. Other than that, not much info on the bug.

**Comment by triverske** [comment]
I'll look into it, thanks for the issue

**Comment by triverske** [comment]
Fixed in 225f0d2
