### ISSUE TITLE
Crash During Quick Match

### ISSUE THREAD

**Issue by Crackshaw** [triverske/ultimatearena#50]
So I've been getting a crash message lately that appears randomly.

############################################################################################
FATAL ERROR in
action number 1
of  Step Event0
for object oFighter:

second index out of bounds request 23,256 maximum size is 256
############################################################################################
--------------------------------------------------------------------------------------------
called from - gml_Object_oFighter_Step_0 (line 9)

I've gotten this quite a few times and am wondering what could cause this and if it's been fixed.

**Comment by triverske** [comment]
Thanks for the bug report, this will be fixed in the Staycation Nation update

**Comment by triverske** [comment]
Fixed in 5ddcbc9
