### ISSUE TITLE
Game Setting Off Anti-Virus

### ISSUE THREAD

**Issue by Crackshaw** [triverske/ultimatearena#51]
I've had the game since August 2016. I decided to go with Bitdefender Anti-Virus recently and for some reason, it is blocking Ultimate Arena saying it's a malicious application. Does anyone know what could be setting it off and has this happened with anybody else with their antivirus?

**Comment by triverske** [comment]
I noticed you closed this issue, were you able to find a fix? I have heard of similar cases in the past where people have had problems with the antivirus and I recall sending avast or someone an email about it.

**Comment by Crackshaw** [comment]
No, I haven't. I figured it was a false positive, but the file will not even open.

**Comment by triverske** [comment]
Ok, I've submitted a report to Bitdefender. I'll update this issue when I hear back from them.

**Comment by Crackshaw** [comment]
Alright, I'm re-installing Bitdefender as of late. Could only get it working once the Bitdefender Agent was killed off. Seeing if re-installing will allow it back in.
