### ISSUE TITLE
Pause Function Broken?

### ISSUE THREAD

**Issue by Leprechan12** [triverske/ultimatearena#54]
I was playing the game and paused it so I could read the sudden influx of updates that were happening in-game. When I tried to unpause it, it did nothing. I hit every single button on the bar, but nothing happened. Doesn't always happen, just from time to time. Hope this gets fixed, or maybe I'm just dumb and someone could tell me what I was doing wrong.

**Comment by triverske** [comment]
I'll have a look into this, if you can find a way to replicate the bug consistently let me know. -Troy

**Comment by triverske** [comment]
Got this one fixed in be30f70
