### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by Gmann101** [triverske/ultimatearena#58]
you guys know how when there is a arena event red circle to show where the event is happening at that area?, well it shrinks and then it goes large i wonder why it does that, and i cannot figure out a way how to solve the problem because it is hard, could you guys troubleshoot this thing for me?, i tried getting a screenshot but Steam wouldn't take one for the game, please troubleshoot this for me guys, thanks.

**Comment by triverske** [comment]
Just based off your description it sounds like you're talking about the adjustable event size. When you use the scroll wheel the size of the event circle increases/decreases. This feature is pretty poorly documented but it sounds like what you're running into

**Comment by Gmann101** [comment]
oh okay i will definetly look at that, thanks.

**Comment by triverske** [comment]
Someday I'll write a complete manual, but I'm too lazy at the moment. -TB
