### ISSUE TITLE
Game not updating

### ISSUE THREAD

**Issue by SpookyKitty** [triverske/ultimatearena#60]
My game has not updated to receive the new features of the game. I'm assuming you've released the update because of the language you used when you made the message announcing it. Just message or @ me on Discord once you know the problem.

**Comment by triverske** [comment]
Hey SpookyKitty,

The Custom Edition branch currently has the latest release, please note that this is not a well tested build so bugs may be frequent and severe. To access this branch on Steam use the beta code "ultimatebeta". If you are unfamiliar with Steam's beta system, you'll need to right click on Ultimate Arena in your library, go to properties, and then use this beta code. Sometime this week the main game will receive all the updates when reliability testing is done.
