### ISSUE TITLE
Workshop Not Working

### ISSUE THREAD

**Issue by tannasnod** [triverske/ultimatearena#64]
Not sure where else to put this, but my game on Steam is not pulling or uploading from the Workshop, so many of the characters I downloaded are gone.

**Comment by triverske** [comment]
Hi, thanks for posting.

Does this issue occur with other Steam titles or just Ultimate Arena?

**Comment by tannasnod** [comment]
Just Ultimate Arena, games such as Tabletop Simulator work fine. Nothing has been uploaded to the UA workshop since early April.

**Comment by triverske** [comment]
Tracked down the issue. Fixed by c95f883.

Restart Steam and try the new update.
