### ISSUE TITLE
Updates broke 3 achievements and they are actually unobtainable

### ISSUE THREAD

**Issue by klaritan** [triverske/ultimatearena#65]
The 100 & 200 land mine kill achievements simply don't work.

At some point, the developer increased the chance of characters committing suicide, and characters will never be able to reach -50% sanity.

**Comment by triverske** [comment]
Thanks for bringing this to our attention. We've got a pretty sizable bugfix update coming soon and we'll update this issue when it comes out.

**Comment by klaritan** [comment]
Thank you. Looking forward for the fix!

**Comment by triverske** [comment]
This has been fixed as of a498f73, the build with these fixes should go live in the next few days. Thanks again for helping us keep track of bugs.
