### ISSUE TITLE
Crash Bug 

### ISSUE THREAD

**Issue by quacket** [triverske/ultimatearena#66]
Probably has already been mentioned however there is a game crashing bug by simply clicking the "Graph" button (apologies can't remember the actual name, where the game crashes and displays:

___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Draw Event
for object obj_uiWindowCaption:

STRING argument is unset
############################################################################################
--------------------------------------------------------------------------------------------
called from - gml_Object_obj_uiWindowCaption_Draw_0 (line 8)
called from - gml_Script_zui_draw (line 14)
called from - gml_Script_zui_draw (line 19)
called from - gml_Script_zui_draw (line 19)
called from - gml_Object_obj_uiMain_Draw_64 (line 4)

Thanks in advance

**Comment by triverske** [comment]
I appreciate the bug report, I'll update this issue when the patch that fixes it is out.

**Comment by triverske** [comment]
This has been fixed as of dff546f, the build with these fixes should go live in the next few days. Thanks again for helping us keep track of bugs.
