### ISSUE TITLE
Wrong number of arguments for function buffer_get_surface

### ISSUE THREAD

**Issue by Kr3m** [triverske/ultimatearena#67]
I'm getting the following error:

Object: obj_maptest Event: Create at line 51 : wrong number of arguments for function buffer_get_surface

`buffer_get_surface(hBuff, heightSurf,0,8,0);`

The third parameter should be the offset, so I'm wondering why there are 3 params following the surface param as opposed to just the offset and how to correct this.

**Comment by triverske** [comment]
Hey there.

I was looking through the GMS2 docs, and it looks like buffer_get_surface uses 3 arguments in GMS2 vs the 5 in GMS1.4

[https://manual.yoyogames.com/GameMaker_Language/GML_Reference/Buffers/buffer_get_surface.htm](GMS2 Docs)
[https://yal.cc/gamemaker-buffer-get-set-surface-2-3-1/](I also found this article on how to navigate these issues in GMS2)

I currently don't have plans to support GMS2 with Ultimate Arena as it's at the end of its product life, but hopefully this can help.

-TB
